Use `\copy` instead of `copy` to upload data with the `postgres` role
With the recent Supabase migration, where the `postgres` role is no longer a `superuser`, the "COPY" commands throws an error 
```
ERROR:  must be superuser or a member of the pg_read_server_files role to COPY from a file
HINT:  Anyone can COPY to stdout or from stdin. psql's \copy command also works for anyone.
```