Missing null check for realtime publication tables
This issue is happening on my production project and prevents me to see the database page:

```
TypeError: Cannot read properties of null (reading 'find')
    at TableList.tsx:169:47
```